const upiId = '9470258885@ybl';
let programs = {}; let screenshotData = null; let adminPassword = '';
const money = n => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(n);
const escapeHtml = value => String(value || '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function api(url, options = {}) { const r = await fetch(url, options); const data = await r.json(); if (!r.ok) throw new Error(data.error || 'Something went wrong.'); return data; }
function updatePayment() { const p = programs[program.value]; if (!p) { amountLine.textContent = 'Select a program to see your amount.'; qr.removeAttribute('src'); return; } amountLine.textContent = `Pay ${money(p.fee)} for ${p.name}.`; const upi = `upi://pay?pa=${encodeURIComponent(upiId)}&pn=${encodeURIComponent('Aspirant Open School')}&am=${p.fee}&cu=INR&tn=${encodeURIComponent('Admission fee')}`; qr.src = `https://quickchart.io/qr?size=220&text=${encodeURIComponent(upi)}`; }
function paymentMode() { const full = document.querySelector('input[name="paymentMode"]:checked').value === 'full'; paymentBox.hidden = !full; proofFields.hidden = !full; utr.required = full; screenshotFile.required = full; }
function selectProgram(key) { const p = programs[key]; if (!p) return; program.value = key; document.querySelectorAll('.tab-btn').forEach(b => b.classList.toggle('active', b.dataset.program === key)); programLine.textContent = `Applying for: ${p.name} — ${money(p.fee)}`; updatePayment(); }
async function init() {
  programs = await api('/api/programs');
  priceCards.innerHTML = Object.entries(programs).map(([key,p]) => `<article><h3>${escapeHtml(p.name)}</h3><strong>${money(p.fee)}</strong><button class="text-button" data-program="${key}">Choose program</button></article>`).join('');
  programTabs.innerHTML = Object.entries(programs).map(([key,p]) => `<button type="button" class="tab-btn" data-program="${key}">${escapeHtml(p.name.split(' — ')[0])}</button>`).join('');
  document.querySelectorAll('[data-program]').forEach(b => b.onclick = () => { selectProgram(b.dataset.program); location.hash = 'apply'; });
}
document.querySelectorAll('input[name="paymentMode"]').forEach(x => x.onchange = paymentMode);
screenshotFile.onchange = () => { const f = screenshotFile.files[0]; if (!f) return screenshotData = null; if (f.size > 2 * 1024 * 1024) { screenshotFile.value = ''; return formMessage.textContent = 'Screenshot must be smaller than 2 MB.'; } const reader = new FileReader(); reader.onload = () => screenshotData = reader.result; reader.readAsDataURL(f); };
applicationForm.onsubmit = async e => { e.preventDefault(); if (!program.value) { formMessage.textContent = 'Please select a class/program tab above first.'; return; } formMessage.textContent = 'Submitting…'; const data = Object.fromEntries(new FormData(applicationForm)); data.screenshot = screenshotData; delete data.screenshotFile; try { const result = await api('/api/applications', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(data) }); formMessage.innerHTML = `Application submitted. Your ID is <strong>${result.id}</strong>. Status: <strong>Payment verification pending</strong>. Save this ID to track approval.`; applicationForm.reset(); screenshotData = null; paymentMode(); } catch (err) { formMessage.textContent = err.message; } };
statusForm.onsubmit = async e => { e.preventDefault(); statusResult.textContent = 'Checking…'; try { const x = await api(`/api/status/${encodeURIComponent(statusId.value.trim())}?phone=${encodeURIComponent(statusPhone.value.trim())}`); statusResult.innerHTML = `<h3>${escapeHtml(x.name)} · ${escapeHtml(x.programName)}</h3><p>Amount: ${money(x.amount)} · Updated: ${new Date(x.updatedAt).toLocaleString('en-IN')}</p><p class="badge ${x.status}">${x.status === 'approved' ? 'Payment confirmed' : x.status === 'rejected' ? 'Payment not verified' : 'Payment verification pending'}</p>${x.adminNote ? `<p>${escapeHtml(x.adminNote)}</p>` : ''}`; } catch (err) { statusResult.textContent = err.message; } };
adminLogin.onsubmit = async e => { e.preventDefault(); adminPassword = adminPasswordInput.value; try { await loadAdmin(); } catch (err) { adminList.textContent = err.message; } };
async function loadAdmin() { const apps = await api('/api/admin/applications', {headers:{'x-admin-password':adminPassword}}); adminList.innerHTML = apps.length ? apps.map(x => `<article class="admin-card"><div><strong>${escapeHtml(x.name)}</strong><br><small>${escapeHtml(x.id)} · ${escapeHtml(x.phone)} · ${money(x.amount)}</small><p>${escapeHtml(x.programName)} · UTR: ${escapeHtml(x.utr || 'EMI request')}</p>${x.screenshot ? `<img src="${x.screenshot}" alt="Payment screenshot for ${escapeHtml(x.name)}">` : ''}</div><div><select data-status="${x.id}"><option value="pending" ${x.status==='pending'?'selected':''}>Pending</option><option value="approved" ${x.status==='approved'?'selected':''}>Approve payment</option><option value="rejected" ${x.status==='rejected'?'selected':''}>Reject</option></select><input data-note="${x.id}" placeholder="Optional note" value="${escapeHtml(x.adminNote)}"><button class="button secondary" data-save="${x.id}">Save decision</button></div></article>`).join('') : '<p>No applications yet.</p>'; document.querySelectorAll('[data-save]').forEach(b => b.onclick = async () => { const id = b.dataset.save; try { await api('/api/admin/applications',{method:'PATCH',headers:{'Content-Type':'application/json','x-admin-password':adminPassword},body:JSON.stringify({id,status:document.querySelector(`[data-status="${id}"]`).value,adminNote:document.querySelector(`[data-note="${id}"]`).value})}); await loadAdmin(); } catch(err) { alert(err.message); } }); }
const programTabs = document.getElementById('programTabs'), programLine = document.getElementById('programLine');
const adminPasswordInput = document.getElementById('adminPassword'); init().then(paymentMode).catch(err => formMessage.textContent = err.message);
